CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    account_non_expired BOOLEAN NOT NULL DEFAULT TRUE,
    account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
    credentials_non_expired BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS authority (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_authority (
    user_id BIGINT NOT NULL,
    authority_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, authority_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (authority_id) REFERENCES authority(id)
);

CREATE TABLE IF NOT EXISTS client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(200),
    phone VARCHAR(30),
    notes VARCHAR(1000),
    user_id BIGINT UNIQUE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE client ADD COLUMN IF NOT EXISTS user_id BIGINT UNIQUE REFERENCES users(id);

CREATE TABLE IF NOT EXISTS location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    county VARCHAR(255),
    country VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS gear_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    notes VARCHAR(1000),
    owner_user_id BIGINT NOT NULL,
    FOREIGN KEY (owner_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS shoot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ,
    notes VARCHAR(2000),
    owner_user_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (owner_user_id) REFERENCES users(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (client_id) REFERENCES client(id),
    CONSTRAINT chk_shoot_dates CHECK (end_at IS NULL OR end_at >= start_at)
);

ALTER TABLE shoot ADD COLUMN IF NOT EXISTS client_id BIGINT REFERENCES client(id);
ALTER TABLE shoot DROP CONSTRAINT IF EXISTS chk_shoot_dates;
-- Keep legacy rows readable while enforcing the rule for every new or updated row.
ALTER TABLE shoot ADD CONSTRAINT chk_shoot_dates CHECK (end_at IS NULL OR end_at >= start_at) NOT VALID;

CREATE TABLE IF NOT EXISTS shoot_gear (
    shoot_id BIGINT NOT NULL,
    gear_item_id BIGINT NOT NULL,
    PRIMARY KEY (shoot_id, gear_item_id),
    FOREIGN KEY (shoot_id) REFERENCES shoot(id),
    FOREIGN KEY (gear_item_id) REFERENCES gear_item(id)
);

CREATE TABLE IF NOT EXISTS media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoot_id BIGINT NOT NULL,
    media_type VARCHAR(30) NOT NULL,
    file_ref VARCHAR(500) NOT NULL,
    taken_at TIMESTAMPTZ,
    iso INTEGER,
    aperture DOUBLE PRECISION,
    shutter_speed VARCHAR(255),
    focal_length INTEGER,
    focal_length35mm INTEGER,
    width_px INTEGER,
    height_px INTEGER,
    rating INTEGER,
    notes VARCHAR(1000),
    duration_seconds INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (shoot_id) REFERENCES shoot(id)
);

CREATE TABLE IF NOT EXISTS invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoot_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    paid_at TIMESTAMPTZ,
    status VARCHAR(50) NOT NULL,
    details VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT unique_invoice_shoot UNIQUE (shoot_id),
    FOREIGN KEY (shoot_id) REFERENCES shoot(id),
    FOREIGN KEY (client_id) REFERENCES client(id)
);
