CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL,
                       password VARCHAR(100) NOT NULL,
                       enabled BOOLEAN NOT NULL DEFAULT true,
                       account_non_expired BOOLEAN NOT NULL DEFAULT true,
                       account_non_locked BOOLEAN NOT NULL DEFAULT true,
                       credentials_non_expired BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE authority (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           role VARCHAR(50) NOT NULL
);

CREATE TABLE user_authority (
                                user_id BIGINT NOT NULL,
                                authority_id BIGINT NOT NULL,

                                PRIMARY KEY (user_id, authority_id),

                                FOREIGN KEY (user_id) REFERENCES users(id),
                                FOREIGN KEY (authority_id) REFERENCES authority(id)
);